# German translations for vigilo-turbogears.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-turbogears
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-turbogears 3.5.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 12:48+0100\n"
"PO-Revision-Date: 2015-05-21 11:47+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/turbogears/helpers.py:89
#, python-format
msgid "Failed to get URL: %s"
msgstr "URL: %s konnte nicht geholt werden"

#: src/vigilo/turbogears/helpers.py:102
#, python-format
msgid ""
"Failed to convert DS %(ds)s on %(host)s: value was %(value)s (max: "
"%(max)s)"
msgstr ""
"DS %(ds)s auf %(host)s konnte nicht umgewandelt werden: Wert %(value)s "
"(max: %(max)s)"

#: src/vigilo/turbogears/helpers.py:133
#, python-format
msgid "high-level service \"%s\""
msgstr ""

#: src/vigilo/turbogears/helpers.py:135
#, python-format
msgid "host \"%s\""
msgstr ""

#: src/vigilo/turbogears/helpers.py:137
#, python-format
msgid "service \"%(service)s\" on host \"%(host)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:34
msgid "Wrong credentials"
msgstr "Ungültige Anmeldeinformationen"

#: src/vigilo/turbogears/controllers/auth.py:49
#, python-format
msgid "\"%(username)s\" logged into %(app)s (from %(IP)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:54
#, python-format
msgid "Welcome back, %s!"
msgstr "Willkommen  %s!"

#: src/vigilo/turbogears/controllers/auth.py:67
#, python-format
msgid "Some user logged out from %(app)s (from %(IP)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:69
#, python-format
msgid "\"%(username)s\" logged out from %(app)s (from %(IP)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:77
msgid "We hope to see you soon!"
msgstr "Bis bald!"

#: src/vigilo/turbogears/controllers/custom.py:40
#, python-format
msgid "Not a valid controller name: %s"
msgstr ""

#: src/vigilo/turbogears/controllers/custom.py:51
#, python-format
msgid "%(entry)s is not a subclass of %(base)s"
msgstr ""

#: src/vigilo/turbogears/controllers/error.py:30
msgid "We're sorry but we weren't able to process this request."
msgstr "Leider kann diese Anforderung nicht verarbeitet werden."

#: src/vigilo/turbogears/controllers/proxy.py:134
#, python-format
msgid ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:149
#, python-format
msgid "No such monitored host: %s"
msgstr "Überwachter Host: %s nicht vorhanden"

#: src/vigilo/turbogears/controllers/proxy.py:168
#, python-format
msgid "Access denied to host \"%(host)s\" and service \"%(service)s\""
msgstr "Zugang zu Host \"%(host)s\" und Service \"%(service)s\" verweigert"

#: src/vigilo/turbogears/controllers/proxy.py:174
#, python-format
msgid "Access denied to host \"%s\""
msgstr "Zugang zu Host \"%s\" verweigert"

#: src/vigilo/turbogears/controllers/proxy.py:192
#, python-format
msgid "No server configured to monitor \"%(host)s\" for application \"%(app)s\""
msgstr "Es wurde kein %(app)s Server zur Überwachung von \"%(host)s\" konfiguriert"

#: src/vigilo/turbogears/controllers/proxy.py:227
#, python-format
msgid "Invalid value for app_redirect.%s, not redirecting."
msgstr "Ungültiger Wert für app_redirect.%s, wird nicht umgeleitet."

#: src/vigilo/turbogears/controllers/proxy.py:233
#, python-format
msgid "Fetching '%s' through the proxy"
msgstr "'%s' wird über den Proxy abgerufen"

#: src/vigilo/turbogears/controllers/proxy.py:256
msgid "Basic authentication to the proxy."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:259
msgid "Digest authentication to the proxy."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:276
msgid "Basic authentication to the website."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:279
msgid "Digest authentication to the website."
msgstr ""

#: src/vigilo/turbogears/controllers/selfmonitoring.py:36
#: src/vigilo/turbogears/controllers/api/root.py:63
msgid "You need to be authenticated"
msgstr "Sie müssen sich authentifizieren"

#: src/vigilo/turbogears/controllers/selfmonitoring.py:40
#, python-format
msgid "You don't have access to %s"
msgstr ""

#: src/vigilo/turbogears/controllers/selfmonitoring.py:49
#, python-format
msgid "Vigilo has detected a breakdown on the following collector(s): %(list)s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:130
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:140
#, python-format
msgid "Remote user: %s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:148
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:158
msgid "Beaker must be present in the WSGI middleware stack for the cache to work"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:162
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:172
msgid "Exception while contacting LDAP server"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:182
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:192
#, python-format
msgid "New user created: %s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:186
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:196
msgid "Exception during user creation"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:195
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:205
#, python-format
msgid "Removing user \"%(user)s\" from group \"%(group)s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:222
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:232
#, python-format
msgid "Creating group \"%s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:230
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:240
#, python-format
msgid "Adding user \"%(user)s\" to group \"%(group)s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:247
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:257
msgid "Exception during groups creation"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:295
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:307
#, python-format
msgid "Bound to the LDAP server as '%s'"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:323
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:334
#, python-format
msgid "User \"%s\" not found in the LDAP server"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:359
#, python-format
msgid "Could not retrieve groups from LDAP server for \"%s\""
msgstr ""

#: src/vigilo/turbogears/rum/fields/group_relation.py:126
#: src/vigilo/turbogears/rum/fields/group_relation.py:150
msgid "Groups of monitored items"
msgstr ""

#: src/vigilo/turbogears/rum/fields/group_relation.py:129
#: src/vigilo/turbogears/rum/fields/group_relation.py:155
msgid "Groups of maps"
msgstr ""

#~ msgid "Basic authentification to the proxy."
#~ msgstr ""

#~ msgid "Digest authentification to the proxy."
#~ msgstr ""

#~ msgid "Basic authentification to the website."
#~ msgstr ""

#~ msgid "Digest authentification to the website."
#~ msgstr ""

