# Translations template for vigilo-turbogears.
# Copyright (C) 2011 ORGANIZATION
# This file is distributed under the same license as the vigilo-turbogears
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-turbogears 2.0.8\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2011-11-22 13:21+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/turbogears/helpers.py:87
#, python-format
msgid "Failed to get URL: %s"
msgstr ""

#: src/vigilo/turbogears/helpers.py:100
#, python-format
msgid "Failed to convert DS %(ds)s on %(host)s: value was %(value)s (max: %(max)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:25
msgid "Wrong credentials"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:39
#, python-format
msgid "\"%(username)s\" logged into %(app)s (from %(IP)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:44
#, python-format
msgid "Welcome back, %s!"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:56
#, python-format
msgid "Some user logged out from %(app)s (from %(IP)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:58
#, python-format
msgid "\"%(username)s\" logged out from %(app)s (from %(IP)s)"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:65
msgid "We hope to see you soon!"
msgstr ""

#: src/vigilo/turbogears/controllers/error.py:30
msgid "We're sorry but we weren't able to process this request."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:135
#, python-format
msgid ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:150
#, python-format
msgid "No such monitored host: %s"
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:170
#, python-format
msgid "Access denied to host \"%(host)s\" and service \"%(service)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:176
#, python-format
msgid "Access denied to host \"%s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:194
#, python-format
msgid "No server configured to monitor \"%(host)s\" for application \"%(app)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:229
#, python-format
msgid "Invalid value for app_redirect.%s, not redirecting."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:235
#, python-format
msgid "Fetching '%s' through the proxy"
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:258
msgid "Basic authentification to the proxy."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:261
msgid "Digest authentification to the proxy."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:278
msgid "Basic authentification to the website."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:281
msgid "Digest authentification to the website."
msgstr ""

#: src/vigilo/turbogears/controllers/api/root.py:63
msgid "You need to be authenticated"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:130
#, python-format
msgid "Remote user: %s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:148
msgid "Beaker must be present in the WSGI middleware stack for the cache to work"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:162
msgid "Exception while contacting LDAP server"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:182
#, python-format
msgid "New user created: %s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:185
msgid "Exception during user creation"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:194
#, python-format
msgid "Removing user \"%(user)s\" from group \"%(group)s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:208
#, python-format
msgid "Creating group \"%s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:216
#, python-format
msgid "Adding user \"%(user)s\" to group \"%(group)s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:233
msgid "Exception during groups creation"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:280
#, python-format
msgid "Bound to the LDAP server as '%s'"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:304
#, python-format
msgid "User \"%s\" not found in the LDAP server"
msgstr ""

#: src/vigilo/turbogears/rum/fields/group_relation.py:126
#: src/vigilo/turbogears/rum/fields/group_relation.py:150
msgid "Groups of monitored items"
msgstr ""

#: src/vigilo/turbogears/rum/fields/group_relation.py:129
#: src/vigilo/turbogears/rum/fields/group_relation.py:155
msgid "Groups of maps"
msgstr ""

