# Translations template for vigilo-turbogears.
# Copyright (C) 2017 ORGANIZATION
# This file is distributed under the same license as the vigilo-turbogears
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2017.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-turbogears 4.1.0rc2\n"
"Report-Msgid-Bugs-To: support.vigilo@csgroup.eu\n"
"POT-Creation-Date: 2017-08-24 14:39+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: support.vigilo@csgroup.eu\n"
"Language-Team: LANGUAGE <support.vigilo@csgroup.eu>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/turbogears/helpers.py:122
#, python-format
msgid "high-level service \"%s\""
msgstr ""

#: src/vigilo/turbogears/helpers.py:124
#, python-format
msgid "host \"%s\""
msgstr ""

#: src/vigilo/turbogears/helpers.py:126
#, python-format
msgid "service \"%(service)s\" on host \"%(host)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:34
msgid "Wrong credentials"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:65
#, python-format
msgid "Welcome back, %s!"
msgstr ""

#: src/vigilo/turbogears/controllers/auth.py:74
msgid "We hope to see you soon!"
msgstr ""

#: src/vigilo/turbogears/controllers/custom.py:40
#, python-format
msgid "Not a valid controller name: %s"
msgstr ""

#: src/vigilo/turbogears/controllers/custom.py:51
#, python-format
msgid "%(entry)s is not a subclass of %(base)s"
msgstr ""

#: src/vigilo/turbogears/controllers/error.py:30
msgid "We're sorry but we weren't able to process this request."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:103
#, python-format
msgid ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:118
#, python-format
msgid "No such monitored host: %s"
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:137
#, python-format
msgid "Access denied to host \"%(host)s\" and service \"%(service)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:143
#, python-format
msgid "Access denied to host \"%s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:161
#, python-format
msgid "No server configured to monitor \"%(host)s\" for application \"%(app)s\""
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:196
#, python-format
msgid "Invalid value for app_redirect.%s, not redirecting."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:202
#, python-format
msgid "Fetching '%s' through the proxy"
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:225
msgid "Basic authentication to the proxy."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:228
msgid "Digest authentication to the proxy."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:245
msgid "Basic authentication to the website."
msgstr ""

#: src/vigilo/turbogears/controllers/proxy.py:248
msgid "Digest authentication to the website."
msgstr ""

#: src/vigilo/turbogears/controllers/selfmonitoring.py:36
#: src/vigilo/turbogears/controllers/api/root.py:63
msgid "You need to be authenticated"
msgstr ""

#: src/vigilo/turbogears/controllers/selfmonitoring.py:40
#, python-format
msgid "You don't have access to %s"
msgstr ""

#: src/vigilo/turbogears/controllers/selfmonitoring.py:49
#, python-format
msgid "Vigilo has detected a breakdown on the following collector(s): %(list)s"
msgstr ""

#: src/vigilo/turbogears/controllers/sprox.py:25
msgid "Administration"
msgstr ""

#: src/vigilo/turbogears/controllers/sprox.py:43
msgid "Are you sure?"
msgstr ""

#: src/vigilo/turbogears/controllers/sprox.py:44
msgid "Edit"
msgstr ""

#: src/vigilo/turbogears/controllers/sprox.py:45
msgid "Delete"
msgstr ""

#: src/vigilo/turbogears/controllers/sprox.py:91
msgid "Submit"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:147
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:170
#, python-format
msgid "Remote user: %s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:165
msgid "Beaker must be present in the WSGI middleware stack for the cache to work"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:179
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:179
msgid "Exception while contacting LDAP server"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:199
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:199
#, python-format
msgid "New user created: %s"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:203
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:203
msgid "Exception during user creation"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:212
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:212
#, python-format
msgid "Removing user \"%(user)s\" from group \"%(group)s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:239
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:236
#, python-format
msgid "Creating group \"%s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:247
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:244
#, python-format
msgid "Adding user \"%(user)s\" to group \"%(group)s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:264
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:261
msgid "Exception during groups creation"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:292
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:288
#, python-format
msgid "Attempting connection to \"%s\""
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:320
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:316
#, python-format
msgid "Could not connect to LDAP server '%s', trying next server"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:325
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:321
msgid "No more LDAP servers to try"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:369
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:375
#, python-format
msgid "User \"%s\" not found in the LDAP server"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:348
#, python-format
msgid "Bound to the LDAP server as '%s'"
msgstr ""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:400
#, python-format
msgid "Could not retrieve groups from LDAP server for \"%s\""
msgstr ""

#: src/vigilo/turbogears/sprox/fields.py:17
#: src/vigilo/turbogears/sprox/fields.py:24
msgid "Read-only"
msgstr ""

#: src/vigilo/turbogears/sprox/fields.py:17
#: src/vigilo/turbogears/sprox/fields.py:24
msgid "Read/write"
msgstr ""

#: src/vigilo/turbogears/sprox/fields.py:98
msgid "Monitoring groups"
msgstr ""

#: src/vigilo/turbogears/sprox/fields.py:101
msgid "Map groups"
msgstr ""

#: src/vigilo/turbogears/sprox/fields.py:104
msgid "Graph groups"
msgstr ""

