# French (France) translations for vigilo-turbogears.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-turbogears
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-turbogears 2.0.0\n"
"Report-Msgid-Bugs-To: support.vigilo@csgroup.eu\n"
"POT-Creation-Date: 2010-07-26 13:47+0200\n"
"PO-Revision-Date: 2017-08-24 14:39+0200\n"
"Last-Translator: support.vigilo@csgroup.eu\n"
"Language-Team: fr_FR <support.vigilo@csgroup.eu>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/turbogears/helpers.py:122
#, python-format
msgid "high-level service \"%s\""
msgstr "service de haut niveau \"%s\""

#: src/vigilo/turbogears/helpers.py:124
#, python-format
msgid "host \"%s\""
msgstr "hôte \"%s\""

#: src/vigilo/turbogears/helpers.py:126
#, python-format
msgid "service \"%(service)s\" on host \"%(host)s\""
msgstr "service \"%(service)s\" de l'hôte \"%(host)s\""

#: src/vigilo/turbogears/controllers/auth.py:34
msgid "Wrong credentials"
msgstr "Identifiant ou mot de passe incorrect"

#: src/vigilo/turbogears/controllers/auth.py:65
#, python-format
msgid "Welcome back, %s!"
msgstr "Bienvenue %s !"

#: src/vigilo/turbogears/controllers/auth.py:74
msgid "We hope to see you soon!"
msgstr "Nous espérons vous revoir bientôt !"

#: src/vigilo/turbogears/controllers/custom.py:40
#, python-format
msgid "Not a valid controller name: %s"
msgstr "Nom de contrôleur non valide : %s"

#: src/vigilo/turbogears/controllers/custom.py:51
#, python-format
msgid "%(entry)s is not a subclass of %(base)s"
msgstr "%(entry)s n'est pas une sous-classe de %(base)s"

#: src/vigilo/turbogears/controllers/error.py:30
msgid "We're sorry but we weren't able to process this request."
msgstr "Nous sommes désolés, mais nous n'avons pas pu traiter votre requête."

#: src/vigilo/turbogears/controllers/proxy.py:103
#, python-format
msgid ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""
msgstr ""
"Aucun serveur configuré pour superviser les services de haut niveau pour "
"l'application \"%(app)s\""

#: src/vigilo/turbogears/controllers/proxy.py:118
#, python-format
msgid "No such monitored host: %s"
msgstr "Hôte supervisé inexistant : %s"

#: src/vigilo/turbogears/controllers/proxy.py:137
#, python-format
msgid "Access denied to host \"%(host)s\" and service \"%(service)s\""
msgstr "Accès refusé au service \"%(service)s\" sur l'hôte \"%(host)s\""

#: src/vigilo/turbogears/controllers/proxy.py:143
#, python-format
msgid "Access denied to host \"%s\""
msgstr "Accès refusé à l'hôte \"%s\""

#: src/vigilo/turbogears/controllers/proxy.py:161
#, python-format
msgid "No server configured to monitor \"%(host)s\" for application \"%(app)s\""
msgstr ""
"Aucun serveur configuré pour superviser \"%(host)s\" pour l'application "
"\"%(app)s\""

#: src/vigilo/turbogears/controllers/proxy.py:196
#, python-format
msgid "Invalid value for app_redirect.%s, not redirecting."
msgstr "Valeur incorrecte pour app_redirect.%s, pas de redirection."

#: src/vigilo/turbogears/controllers/proxy.py:202
#, python-format
msgid "Fetching '%s' through the proxy"
msgstr "Récupération de '%s' via le serveur mandataire"

#: src/vigilo/turbogears/controllers/proxy.py:225
msgid "Basic authentication to the proxy."
msgstr "Authentification de type Basic auprès du serveur mandataire."

#: src/vigilo/turbogears/controllers/proxy.py:228
msgid "Digest authentication to the proxy."
msgstr "Authentification de type Digest auprès du serveur mandataire."

#: src/vigilo/turbogears/controllers/proxy.py:245
msgid "Basic authentication to the website."
msgstr "Authentification de type Basic auprès du site distant."

#: src/vigilo/turbogears/controllers/proxy.py:248
msgid "Digest authentication to the website."
msgstr "Authentification de type Digest auprès du site distant."

#: src/vigilo/turbogears/controllers/selfmonitoring.py:36
#: src/vigilo/turbogears/controllers/api/root.py:63
msgid "You need to be authenticated"
msgstr "Vous devez vous authentifier"

#: src/vigilo/turbogears/controllers/selfmonitoring.py:40
#, python-format
msgid "You don't have access to %s"
msgstr "Vous n'avez les permissions suffisantes pour accéder à %s"

#: src/vigilo/turbogears/controllers/selfmonitoring.py:49
#, python-format
msgid "Vigilo has detected a breakdown on the following collector(s): %(list)s"
msgstr "Vigilo a détecté une panne sur le(s) collecteur(s) suivant(s) : %(list)s"

#: src/vigilo/turbogears/controllers/sprox.py:25
msgid "Administration"
msgstr "Administration"

#: src/vigilo/turbogears/controllers/sprox.py:43
msgid "Are you sure?"
msgstr "Êtes-vous sûr(e) ?"

#: src/vigilo/turbogears/controllers/sprox.py:44
msgid "Edit"
msgstr "Modifier"

#: src/vigilo/turbogears/controllers/sprox.py:45
msgid "Delete"
msgstr "Supprimer"

#: src/vigilo/turbogears/controllers/sprox.py:91
msgid "Submit"
msgstr "Envoyer"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:147
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:170
#, python-format
msgid "Remote user: %s"
msgstr "Utilisateur externe : %s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:165
msgid "Beaker must be present in the WSGI middleware stack for the cache to work"
msgstr "Beaker doit être présent dans la pile WSGI pour que le cache fonctionne"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:179
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:179
msgid "Exception while contacting LDAP server"
msgstr "Exception lors de la communication avec le serveur LDAP"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:199
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:199
#, python-format
msgid "New user created: %s"
msgstr "Nouveau utilisateur créé : %s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:203
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:203
msgid "Exception during user creation"
msgstr "Exception lors de la création de l'utilisateur"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:212
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:212
#, python-format
msgid "Removing user \"%(user)s\" from group \"%(group)s\""
msgstr "Retrait de l'utilisateur \"%(user)s\" du groupe \"%(group)s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:239
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:236
#, python-format
msgid "Creating group \"%s\""
msgstr "Création du groupe \"%s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:247
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:244
#, python-format
msgid "Adding user \"%(user)s\" to group \"%(group)s\""
msgstr "Ajout de l'utilisateur \"%(user)s\" au groupe \"%(group)s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:264
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:261
msgid "Exception during groups creation"
msgstr "Exception lors de la création des groupes"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:292
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:288
#, python-format
msgid "Attempting connection to \"%s\""
msgstr "Tentative de connexion à \"%s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:320
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:316
#, python-format
msgid "Could not connect to LDAP server '%s', trying next server"
msgstr ""
"Impossible de se connecter au serveur LDAP '%s', essai avec le serveur "
"suivant"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:325
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:321
msgid "No more LDAP servers to try"
msgstr "Plus aucun serveur LDAP à tester"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:369
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:375
#, python-format
msgid "User \"%s\" not found in the LDAP server"
msgstr "L'utilisateur \"%s\" est introuvable sur le serveur LDAP"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:348
#, python-format
msgid "Bound to the LDAP server as '%s'"
msgstr "Lié au serveur LDAP en tant que '%s'"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:400
#, python-format
msgid "Could not retrieve groups from LDAP server for \"%s\""
msgstr "Impossible de récupérer les groupes depuis l'annuaire LDAP pour \"%s\""

#: src/vigilo/turbogears/sprox/fields.py:17
#: src/vigilo/turbogears/sprox/fields.py:24
msgid "Read-only"
msgstr "Lecture seule"

#: src/vigilo/turbogears/sprox/fields.py:17
#: src/vigilo/turbogears/sprox/fields.py:24
msgid "Read/write"
msgstr "Lecture/écriture"

#: src/vigilo/turbogears/sprox/fields.py:98
msgid "Monitoring groups"
msgstr "Groupes de supervision"

#: src/vigilo/turbogears/sprox/fields.py:101
msgid "Map groups"
msgstr "Groupes de cartes"

#: src/vigilo/turbogears/sprox/fields.py:104
msgid "Graph groups"
msgstr "Groupes de graphes"

#. TRANSLATORS: Format de date et heure Python/JavaScript.
#. TRANSLATORS:
#. http://www.dynarch.com/static/jscalendar-1.0/doc/html/reference.html#node_sec_5.3.5
#. TRANSLATORS: http://docs.python.org/release/2.5/lib/module-time.html
#: vigiboard/lib/dateformat.py:37
#, python-format
msgid "%Y-%m-%d %I:%M:%S %p"
msgstr "%d/%m/%Y %H:%M:%S"

#. TRANSLATORS: Format de date Python/JavaScript.
#. TRANSLATORS:
#. http://www.dynarch.com/static/jscalendar-1.0/doc/html/reference.html#node_sec_5.3.5
#. TRANSLATORS: http://docs.python.org/release/2.5/lib/module-time.html
#: vigiboard/lib/dateformat.py:66
#, python-format
msgid "%Y-%m-%d"
msgstr "%d/%m/%Y"
