# French (France) translations for vigilo-turbogears.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-turbogears
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-turbogears 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-07-26 13:47+0200\n"
"PO-Revision-Date: 2011-11-22 13:21+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: fr_FR <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/turbogears/helpers.py:87
#, python-format
msgid "Failed to get URL: %s"
msgstr "Impossible d'obtenir le contenu de l'URL: %s"

#: src/vigilo/turbogears/helpers.py:100
#, python-format
msgid ""
"Failed to convert DS %(ds)s on %(host)s: value was %(value)s (max: "
"%(max)s)"
msgstr ""
"Impossible de convertir la DS %(ds)s sur %(host)s: la valeur était "
"%(value)s (max : %(max)s)"

#: src/vigilo/turbogears/controllers/auth.py:25
msgid "Wrong credentials"
msgstr "Identifiant ou mot de passe incorrect"

#: src/vigilo/turbogears/controllers/auth.py:39
#, python-format
msgid "\"%(username)s\" logged into %(app)s (from %(IP)s)"
msgstr "\"%(username)s\" s'est connecté à %(app)s (depuis %(IP)s)"

#: src/vigilo/turbogears/controllers/auth.py:44
#, python-format
msgid "Welcome back, %s!"
msgstr "Bienvenue %s !"

#: src/vigilo/turbogears/controllers/auth.py:56
#, python-format
msgid "Some user logged out from %(app)s (from %(IP)s)"
msgstr "Un utilisateur s'est déconnecté de %(app)s (depuis %(IP)s)"

#: src/vigilo/turbogears/controllers/auth.py:58
#, python-format
msgid "\"%(username)s\" logged out from %(app)s (from %(IP)s)"
msgstr "\"%(username)s\" s'est déconnecté de %(app)s (depuis %(IP)s)"

#: src/vigilo/turbogears/controllers/auth.py:65
msgid "We hope to see you soon!"
msgstr "Nous espérons vous revoir bientôt !"

#: src/vigilo/turbogears/controllers/error.py:30
msgid "We're sorry but we weren't able to process this request."
msgstr "Nous sommes désolés, mais nous n'avons pas pu traiter votre requête."

#: src/vigilo/turbogears/controllers/proxy.py:135
#, python-format
msgid ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""
msgstr ""
"Aucun serveur configuré pour superviser les services de haut niveau pour "
"l'application \"%(app)s\""

#: src/vigilo/turbogears/controllers/proxy.py:150
#, python-format
msgid "No such monitored host: %s"
msgstr "Hôte supervisé inexistant : %s"

#: src/vigilo/turbogears/controllers/proxy.py:170
#, python-format
msgid "Access denied to host \"%(host)s\" and service \"%(service)s\""
msgstr "Accès refusé au service \"%(service)s\" sur l'hôte \"%(host)s\""

#: src/vigilo/turbogears/controllers/proxy.py:176
#, python-format
msgid "Access denied to host \"%s\""
msgstr "Accès refusé à l'hôte \"%s\""

#: src/vigilo/turbogears/controllers/proxy.py:194
#, python-format
msgid "No server configured to monitor \"%(host)s\" for application \"%(app)s\""
msgstr ""
"Aucun serveur configuré pour superviser \"%(host)s\" pour \"\n"
"\"l'application \"%(app)s\""

#: src/vigilo/turbogears/controllers/proxy.py:229
#, python-format
msgid "Invalid value for app_redirect.%s, not redirecting."
msgstr "Valeur incorrecte pour app_redirect.%s, pas de redirection."

#: src/vigilo/turbogears/controllers/proxy.py:235
#, python-format
msgid "Fetching '%s' through the proxy"
msgstr "Récupération de '%s' via le serveur mandataire"

#: src/vigilo/turbogears/controllers/proxy.py:258
msgid "Basic authentification to the proxy."
msgstr "Authentification de type Basic auprès du proxy."

#: src/vigilo/turbogears/controllers/proxy.py:261
msgid "Digest authentification to the proxy."
msgstr "Authentification de type Digest auprès du proxy."

#: src/vigilo/turbogears/controllers/proxy.py:278
msgid "Basic authentification to the website."
msgstr "Authentification de type Basic auprès du site distant."

#: src/vigilo/turbogears/controllers/proxy.py:281
msgid "Digest authentification to the website."
msgstr "Authentification de type Digest auprès du site distant."

#: src/vigilo/turbogears/controllers/api/root.py:63
msgid "You need to be authenticated"
msgstr "Vous devez vous authentifier"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:130
#, python-format
msgid "Remote user: %s"
msgstr "Utilisateur externe : %s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:148
msgid "Beaker must be present in the WSGI middleware stack for the cache to work"
msgstr "Beaker doit être présent dans la pile WSGI pour que le cache fonctionne"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:162
msgid "Exception while contacting LDAP server"
msgstr "Exception lors de la communication avec le serveur LDAP"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:182
#, python-format
msgid "New user created: %s"
msgstr "Nouveau utilisateur créé : %s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:185
msgid "Exception during user creation"
msgstr "Exception lors de la création de l'utilisateur"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:194
#, python-format
msgid "Removing user \"%(user)s\" from group \"%(group)s\""
msgstr "Retrait de l'utilisateur \"%(user)s\" du groupe \"%(group)s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:208
#, python-format
msgid "Creating group \"%s\""
msgstr "Création du groupe \"%s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:216
#, python-format
msgid "Adding user \"%(user)s\" to group \"%(group)s\""
msgstr "Ajout de l'utilisateur \"%(user)s\" au groupe \"%(group)s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:233
msgid "Exception during groups creation"
msgstr "Exception lors de la création des groupes"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:280
#, python-format
msgid "Bound to the LDAP server as '%s'"
msgstr "Lié au serveur LDAP en tant que '%s'"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:304
#, python-format
msgid "User \"%s\" not found in the LDAP server"
msgstr "L'utilisateur \"%s\" est introuvable sur le serveur LDAP"

#: src/vigilo/turbogears/rum/fields/group_relation.py:126
#: src/vigilo/turbogears/rum/fields/group_relation.py:150
msgid "Groups of monitored items"
msgstr "Groupes d'éléments supervisés"

#: src/vigilo/turbogears/rum/fields/group_relation.py:129
#: src/vigilo/turbogears/rum/fields/group_relation.py:155
msgid "Groups of maps"
msgstr "Groupes de cartes"

